### ISSUE TITLE
Doesn't work on Spigot 1.8.8

### ISSUE THREAD

**Issue by greencopper** [vik1395/ProtectionStones#7]
We have change the default block to "IRON_BLOCK", when I user sets the block, and he hasn't set any blocks before, we get:

```
You can not create any more protected regions.
```

The user haven't got any protected regions.

In permissions we just have a default with:

```
    protectionstones.create: true
    protectionstones.destroy: true
    protectionstones.view: true
    protectionstones.info: true
    protectionstones.hide: true
    protectionstones.unhide: true
    protectionstones.home: true
    protectionstones.tp: true
    protectionstones.priority: true
    protectionstones.owners: true
    protectionstones.members: true
    protectionstones.flags: true
    protectionstones.toggle: true
```

If we set:

```
    protectionstones.region: true
```

We still get the same problem.

**Comment by vik1395** [comment]
Hello,
Check to make sure that "protectionstones.limit.x" permission isn't hiding somewhere, it happens often. If not, try giving them a limit and see if they get the same error message. 

Can you also tell me what permissions plugin you are using?

**Comment by greencopper** [comment]
Thank you for replying! :)

I am not using a permission plugin.

My entire permissions look like this:

```
server.basics:
  description: Basic permissions.
  default: true
  children:
    multiverse.teleport.*: true
    multiverse.core.list.who: true
    multiverse.core.list.worlds: true
    multiverse.core.list.environments: true
    multiverse.access.*: true
    multiverse.exempt.*: true
    protectionstones.create: true
    protectionstones.destroy: true
    protectionstones.view: true
    protectionstones.info: true
    protectionstones.hide: true
    protectionstones.unhide: true
    protectionstones.home: true
    protectionstones.tp: true
    protectionstones.priority: true
    protectionstones.owners: true
    protectionstones.members: true
    protectionstones.flags: true
    protectionstones.toggle: true
    protectionstones.region: true
```
Which is working with Multiverse.

There is no "protectionstones.limit.x" anywhere.

Maybe I have done something wrong in my setup?
